CLK_SET_LOW		MACRO
	lda		PD
	and		#$bf
	sta		PD
	ENDM

CLK_SET_HIGH	MACRO
	lda		PD
	ora		#$40
	sta		PD
	ENDM
		
SDI_SET_LOW		MACRO
	lda		PC
	and		#$fd
	sta		PC
	ENDM

SDI_SET_HIGH	MACRO
	lda		PC
	ora		#$02
	sta		PC
	ENDM
		
LE_SET_LOW		MACRO
	lda		PD
	and		#$7f
	sta		PD
	ENDM
		
LE_SET_HIGH		MACRO
	lda		PD
	ora		#$80
	sta		PD
	ENDM


LED_SET_LOW		MACRO
	lda		PC
	and		#$fe
	sta		PC
	ENDM

LED_SET_HIGH	MACRO
	lda		PC
	ora		#$01
	sta		PC
	ENDM
